### ISSUE TITLE
Extend timeouts in proxy.conf

### ISSUE THREAD

**Issue by lbwexler** [xh/xh-nginx#7]
We would like to extend the timeouts imposed by nginx here to something long enough, so that
the value in hoist-react's fetchService will govern the effective timeout received by the user. 

We were thinking 5 minutes, as a reasonable amount that would allow very long client requests, but still
provide some baseline protection for hanging requests.  But that was just a thought.

 ```
       proxy_connect_timeout 300;
        proxy_read_timeout 300;
        proxy_send_timeout 300;
```

**Comment by lbwexler** [comment]
@petradish will want to know when this is complete, so she can remove a workaround in a client app, where she had to copy the entire file in to her project rather than import it.

**Comment by lbwexler** [comment]
Adding @amcclain so he is aware of this

**Comment by amcclain** [comment]
Sounds good to me 👍

**Comment by haynesjm42** [comment]
Timeouts increased to 300s
