### ISSUE TITLE
Intermittent Rendering issue with icons

### ISSUE THREAD

**Issue by lbwexler** [xh/xh-nginx#9]
Reported by a client recently, but also seen intermittently over the past few months by many team members

See https://github.com/FortAwesome/Font-Awesome/issues/17644

**Comment by amcclain** [comment]
I'll bake this into our base image here - still waiting to get confirm from client if they see it again, but if safe it's best to have it built in.

**Comment by amcclain** [comment]
<img width="1504" alt="Screen Shot 2022-01-14 at 9 52 41 AM" src="https://user-images.githubusercontent.com/225806/149562369-4f3f67d5-cf31-4559-b37c-07acc4ef617a.png">

<img width="1506" alt="Screen Shot 2022-01-14 at 9 52 54 AM" src="https://user-images.githubusercontent.com/225806/149562381-c3077f4a-32c7-4060-bc78-8ef6be27b5f4.png">
